# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='authority_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='end_user',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('count', models.BigIntegerField(default=0)),
                ('due', models.BigIntegerField(default=0)),
                ('fine', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tollbooth',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tollbooth_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_truck_count', models.BigIntegerField(default=0)),
                ('four_wheeler_count', models.BigIntegerField(default=0)),
                ('light_commercial_vehicle_count', models.BigIntegerField(default=0)),
                ('multi_axle_vehicle_count', models.BigIntegerField(default=0)),
                ('over_size_vehicle_count', models.BigIntegerField(default=0)),
                ('dateof', models.DateField(auto_now=True)),
                ('income', models.BigIntegerField(default=0)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.tollbooth')),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('name', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.tollbooth')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.end_user')),
            ],
        ),
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.BigIntegerField(default=0)),
                ('fine_paid', models.BigIntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.end_user')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.BigIntegerField(default=0)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.types')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='end_user',
            name='type_of_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.types'),
        ),
        migrations.AddField(
            model_name='end_user',
            name='type_of_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values.vehicle'),
        ),
    ]
