# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_store_from_rpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_from_rpi',
            name='tname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store_from_rpi',
            name='vehicle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
