# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0003_auto_20180415_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store_from_rpi',
        ),
    ]
