# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0004_delete_store_from_rpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='end_user',
            name='fine',
        ),
    ]
