# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0005_remove_end_user_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_log',
            name='fine_paid',
        ),
    ]
